max_width = 100
# yeap
comment_width = 80
wrap_comments = true
hard_tabs = false
tab_spaces = 4
imports_layout = "HorizontalVertical"
merge_imports = true

newline_style = "Unix"
use_small_heuristics = "Default"

reorder_imports = true
reorder_modules = true

remove_nested_parens = true

fn_args_layout = "Tall"

edition = "2018"

merge_derives = true

use_try_shorthand = false
use_field_init_shorthand = false

force_explicit_abi = true
