[workspace]
members = [
  "copy",
  "daemon",
  "data",
  "e2e",
  "git-ext",
  "git-helpers",
  "git-trailers",
  "librad",
  "link-canonical",
  "link-crypto",
  "link-git-protocol",
  "link-identities",
  "macros",
  "rad-clib",
  "rad-exe",
  "rad-profile",
  "seed",
  "std-ext",
  "test",
]

[patch.crates-io.git2]
git = "https://github.com/radicle-dev/git2-rs.git"
rev = "ae027b9e7b125f56397bbb7d8652b3427deeede6"

[patch.crates-io.libgit2-sys]
git = "https://github.com/radicle-dev/git2-rs.git"
rev = "ae027b9e7b125f56397bbb7d8652b3427deeede6"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
