[workspace]
members = [ "librad", "radicle-tracker" ]

[patch.crates-io]
# Ed25519 support for rustls
#
# This needs to be a "patch" so dependencies transitively using rustls also use
# our version.
#
# See https://github.com/ctz/rustls/pull/340
rustls = { git = "https://github.com/kim/rustls", rev = "558405ac3c229947ca17b9285d60368ce67835ce" }
