[workspace]
members = [
  "copy",
  "daemon",
  "data",
  "e2e",
  "git-ext",
  "git-helpers",
  "librad",
  "macros",
  "seed",
  "std-ext",
  "test",
]

[patch.crates-io.git2]
git = "https://github.com/radicle-dev/git2-rs.git"
rev = "5971ca18d73eed39384193899177dfb7ac2d0a05"

[patch.crates-io.libgit2-sys]
git = "https://github.com/radicle-dev/git2-rs.git"
rev = "5971ca18d73eed39384193899177dfb7ac2d0a05"

