[package]
name = "radicle-seed"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
async-trait = "0.1"
crossbeam-utils = "0.8.5"
futures = "0.3"
librad = { path = "../librad" }
radicle-keystore = "0"
signal-hook = "0.3.9"
thiserror = "1"
tokio = { version = "1.1", features = ["time"] }
tokio-stream = { version = "0.1", default-features = false }
tracing = "0.1"
