[package]
name = "radicle-tracker"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonempty = "0.5"
num-bigint = "0.3"
thiserror = "1"

[dev-dependencies]
proptest = "0"
